import streamlit as st
import pandas as pd
import plotly.express as px
from pathlib import Path


# -----------------------------
# Load Forecast Data
# -----------------------------

BASE_DIR = Path(__file__).resolve().parents[2]

FORECAST_PATH = BASE_DIR / "forecasts" / "HHS_Care_7_Day_Forecast.csv"

forecast_df = pd.read_csv(FORECAST_PATH)

forecast_df["Date"] = pd.to_datetime(forecast_df["Date"])

forecast_df = forecast_df.sort_values("Date")

# -----------------------------
# Load Historical Data
# -----------------------------

HISTORICAL_PATH = BASE_DIR / "data" / "HHS_UAC_Cleaned.csv"

historical_df = pd.read_csv(HISTORICAL_PATH)

historical_df["Date"] = pd.to_datetime(
    historical_df["Date"]
)

historical_df = historical_df.sort_values("Date")

# -----------------------------
# Page Title
# -----------------------------

st.title("📈 HHS Care Forecast")

st.write(
    """
    This page presents the seven-day forecast generated by the
    final Random Forest forecasting model.
    """
)

st.divider()


# -----------------------------
# Forecast Summary
# -----------------------------

average_forecast = forecast_df["Predicted HHS Care"].mean()

maximum_forecast = forecast_df["Predicted HHS Care"].max()

minimum_forecast = forecast_df["Predicted HHS Care"].min()

normal_days = (forecast_df["Risk"] == "Normal").sum()

high_risk_days = (forecast_df["Risk"] == "High Risk").sum()


col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(
        "Average Forecast",
        f"{average_forecast:,.0f}"
    )

with col2:
    st.metric(
        "Maximum Forecast",
        f"{maximum_forecast:,.0f}"
    )

with col3:
    st.metric(
        "Minimum Forecast",
        f"{minimum_forecast:,.0f}"
    )

with col4:
    st.metric(
        "High Risk Days",
        high_risk_days
    )


st.divider()

st.subheader("📌 Forecast Summary")

forecast_change = (
    forecast_df["Predicted HHS Care"].iloc[-1]
    - forecast_df["Predicted HHS Care"].iloc[0]
)

if forecast_change > 0:

    st.warning(
        f"HHS care demand is projected to increase by "
        f"{forecast_change:.0f} children over the forecast period."
    )

elif forecast_change < 0:

    st.info(
        f"HHS care demand is projected to decrease by "
        f"{abs(forecast_change):.0f} children over the forecast period."
    )

else:

    st.success(
        "HHS care demand is projected to remain stable."
    )

# -----------------------------
# Historical + Forecast Chart
# -----------------------------

st.subheader("📊 Historical HHS Care + Future Forecast")

fig_combined = px.line(
    historical_df,
    x="Date",
    y="Children in HHS Care",
    title="Historical HHS Care and Seven-Day Forecast"
)

fig_combined.add_scatter(
    x=forecast_df["Date"],
    y=forecast_df["Predicted HHS Care"],
    mode="lines+markers",
    name="Forecast"
)

fig_combined.update_layout(
    xaxis_title="Date",
    yaxis_title="HHS Care",
    hovermode="x unified"
)

st.plotly_chart(
    fig_combined,
    use_container_width=True
)

# -----------------------------
# Forecast Chart
# -----------------------------

st.subheader("🔮 Seven-Day HHS Care Forecast")

fig = px.line(
    forecast_df,
    x="Date",
    y="Predicted HHS Care",
    markers=True,
    text="Predicted HHS Care",
    title="Predicted HHS Care Demand"
)

fig.update_traces(
    texttemplate="%{text:.0f}",
    textposition="top center"
)

fig.update_layout(
    xaxis_title="Date",
    yaxis_title="Predicted HHS Care",
    hovermode="x unified"
)

y_min = forecast_df["Predicted HHS Care"].min()
y_max = forecast_df["Predicted HHS Care"].max()

padding = 5

fig.update_layout(
    xaxis_title="Date",
    yaxis_title="Predicted HHS Care",
    hovermode="x unified",
    yaxis=dict(
        range=[y_min - padding, y_max + padding]
    )
)

st.plotly_chart(
    fig,
    use_container_width=True
)


# -----------------------------
# Forecast Table
# -----------------------------

st.subheader("📋 Forecast Details")

display_df = forecast_df.copy()

display_df["Date"] = display_df["Date"].dt.strftime("%Y-%m-%d")

display_df["Predicted HHS Care"] = (
    display_df["Predicted HHS Care"]
    .round(2)
)

st.dataframe(
    display_df,
    use_container_width=True,
    hide_index=True
)


# -----------------------------
# Risk Summary
# -----------------------------

st.subheader("⚠️ Risk Analysis")

if high_risk_days > 0:

    st.warning(
        f"{high_risk_days} forecast day(s) are classified as High Risk."
    )

else:

    st.success(
        "All seven forecast days are currently classified as Normal risk."
    )


st.divider()

st.caption(
    "Forecast generated using the final Random Forest model."
)